# -*- coding: utf-8 -*-
"""Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgbtWBWMMi-fXCubH03I62oCshy45NeM

1.
1.Artificial Intelligence is technology that enables computers and machines to simulate human learning, comprehension, problem solving, decision making, creativity and autonomy.


2.Machine learning is a branch of Artificial Intelligence  that allows machines to learn and improve from experience. It uses algorithms to analyze data, learn from it, and then make informed decisions.

3.Deep learning is a machine learning technique that uses neural networks to teach computers to process data in a way that mimics the human brain.

2.Supervisied Machine learning is a machine learning technique that uses labeled data to train algorithms to recognize patterns and predict outcomes.
Examples: Image Classification, House Price Prediction.

3.Unsupervised Machine Learning is a machine learing technique in which models are given unlableled data and allowed to predict patterns and insights without any explicit guidance or instruction.


4.Aritificial Intelligence is the field of developing intelligent machines that works without human intervention, machine learing is the subfield of AI that allows machine to learn and improve from given data and come up with a result, Deep learning is the subfield of machine learing that models to mimic human brain using Neural Networks, Data Science is the field that allows to come up to a result from dataset using AI, ML and DL.
  
5.Supersvised machine learing has labeled data as input and includes classification and regression, unsupervised machine learing has unlabeled data as it input and machine make clusters of similar data without explicit instruction whereas semi supervised machine learing is combination of supervised and unsupervised machine learing.

6.Training is the process which is used to train the model by learing patterns and relationships in the data.
Validaiton is the process to evaluate the model performanced and to fine tune the model after each training period.
Testing is the evaluating the performance of the the model using testing dataset and measuring the accuracy of the model.

7.Unsupervised machine learning can be used for anomaly detection to identify unusual patterns or outliers in data without pre-labeled responses using differnt algorithms.
8. Supervised machine learning algorithms:
Linear Regression, Support Vector Machines, Logistical Regression, Decision Trees.
Unsupervised Machine Learning:
K- means Clustering, Hierarchical Clustering and Apriori Algorithm.
"""